name: Test ARM Runner

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          date
          uname -a
          cat /etc/*release
